{
 "title": "Example Server Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Server Active Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(servernew_active_request_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Post Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total Successful Post Requests",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "servernew_request_count_total{status=\"2xx\",method=\"post\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Response Duration (seconds)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "Response Duration (seconds)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(servernew_response_duration_seconds_bucket) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Successful Get Requests",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "servernew_request_count_total{status=\"2xx\",method=\"get\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}