apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: user-server
    tier: mysql
spec:
  ports:
    - port: 3306
  selector:
    app:  user-server
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: user-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: user-server
    tier: mysql
spec:
  selector:
    matchLabels:
      app:  user-server
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app:  user-server
        tier: mysql
    spec:
      containers:
      - image: mysql:8
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: MYSQL_DATABASE
          value: users
        ports:
        - containerPort: 3306
          #---          name: server-mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim

